version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: process.env.DATABASE_URL
      JWT_SECRET: process.env.JWT_SECRET
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: process.env.POSTGRES_DB
    ports:
      - "5432:5432"